export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const TOKEN_REPOSITORY = Symbol('TOKEN_REPOSITORY');
export const PASSWORD_SERVICE = Symbol('PASSWORD_SERVICE');
export const JWT_TOKEN_SERVICE = Symbol('JWT_TOKEN_SERVICE');
